// Generated by CoffeeScript 1.4.0
(function() {
  var TimeRecoverProperty, assert;

  TimeRecoverProperty = require("../../lib/TimeRecoverProperty").TimeRecoverProperty;

  assert = require("assert");

  console.log(this);

  describe('Array', function() {
    return describe('#indexOf()', function() {
      return it('should return -1 when the value is not present', function() {
        var timeProperty;
        assert.equal(-1, [1, 2, 3].indexOf(5));
        assert.equal(-1, [1, 2, 3].indexOf(0));
        timeProperty = new TimeRecoverProperty({
          maxRecoverTime: 1000 * 60,
          curRecoverTime: 0,
          timeToValueRate: 1000
        });
        assert.equal(60, timeProperty.getMaxValue());
        return assert.equal(0, timeProperty.getCurValue());
      });
    });
  });

}).call(this);
